import { describe, it, expect } from 'vitest';
import { zipSync, strToU8 } from 'fflate';
import {
  inspectFile,
  redactFile,
  detectFormat,
  isStructuralFinding,
  scanContent,
  fingerprint,
  exposure,
  estimateTokens,
  UnsupportedFormatError,
  type Finding,
} from '../src/core/index.js';

const find = (findings: Finding[], label: string) => findings.find((f) => f.label === label);
const labels = (findings: Finding[]) => findings.map((f) => f.label);

/* -------------------------------------------------------------- content scan */

describe('content scanning', () => {
  it('finds an API key and never prints it in full', () => {
    const key = `sk-ant-api03-${'A'.repeat(40)}`;
    const [finding] = scanContent(`ANTHROPIC_API_KEY=${key}`, '.env');
    expect(finding?.label).toContain('Anthropic API key');
    expect(finding?.value).not.toContain(key);
    expect(finding?.value).toMatch(/characters\).*rotate/);
    expect(finding?.confidence).toBe('confirmed');
  });

  it('finds provider-issued request identifiers', () => {
    const found = scanContent(`response id msg_${'0'.repeat(24)} logged`, 'log.txt');
    expect(labels(found)).toContain('Anthropic message id');
  });

  it('finds provider endpoints', () => {
    expect(labels(scanContent('POST https://api.anthropic.com/v1/messages', 'x.js'))).toContain(
      'LLM provider endpoint',
    );
  });

  it('stays silent on prose that merely mentions a vendor', () => {
    // A document discussing Claude is not a document produced by Claude, and
    // conflating the two is what makes these tools untrustworthy.
    const prose = 'Nous avons comparé Claude, ChatGPT et Gemini pour ce projet.';
    expect(scanContent(prose, 'body')).toEqual([]);
  });

  it('reports each distinct secret once', () => {
    const key = `sk-ant-api03-${'B'.repeat(40)}`;
    expect(scanContent(`${key} and again ${key}`, 'x')).toHaveLength(1);
  });
});

/* --------------------------------------------------------------- fingerprint */

describe('expanded generator detection', () => {
  const derive = (value: string) =>
    fingerprint([
      { kind: 'provenance', confidence: 'informational', location: 'test', label: 'T', value },
    ]);

  it('names coding agents', () => {
    expect(find(derive('Claude Code 2.1'), 'Coding agent named in metadata')?.value).toBe('Claude Code');
    expect(find(derive('generated by Cursor'), 'Coding agent named in metadata')?.value).toBe('Cursor');
  });

  it('pins the exact model when the identifier is present', () => {
    expect(find(derive('claude-opus-5'), 'Model identifier')?.value).toContain('claude-opus-5');
    expect(find(derive('gpt-4o-mini'), 'Model identifier')?.value).toContain('gpt-4o-mini');
    expect(find(derive('gemini-2.0-flash'), 'Model identifier')?.value).toContain('gemini-2.0-flash');
  });

  it('names frameworks and local runtimes', () => {
    expect(find(derive('LangChain 0.3'), 'LLM framework or runtime')?.value).toBe('LangChain');
    expect(find(derive('served by Ollama'), 'LLM framework or runtime')?.value).toBe('Ollama');
  });

  it('masks a credential found in a metadata field', () => {
    const key = `sk-ant-api03-${'C'.repeat(40)}`;
    const found = derive(`key=${key}`);
    const credential = found.find((f) => f.label.startsWith('Credential left in file'));
    expect(credential).toBeDefined();
    expect(credential?.value).not.toContain(key);
  });

  it('still says nothing about ordinary desktop software', () => {
    expect(derive('Microsoft Office PowerPoint')).toEqual([]);
  });
});

/* ------------------------------------------------------------------ archives */

function makeArchive(): Uint8Array {
  const pptx = zipSync({
    '[Content_Types].xml': strToU8('<Types/>'),
    'docProps/core.xml': strToU8(
      '<cp:coreProperties xmlns:cp="c" xmlns:dc="d"><dc:creator>Lotfi Zakaria</dc:creator></cp:coreProperties>',
    ),
    'ppt/presentation.xml': strToU8('<p:presentation/>'),
  });
  return zipSync({
    'export/deck.pptx': pptx,
    'export/notes.md': strToU8('---\ngenerated_by: claude-opus\n---\n\n# Notes\n'),
    'export/.env': strToU8(`ANTHROPIC_API_KEY=sk-ant-api03-${'D'.repeat(40)}\n`),
    'C:/Users/lotfi/export/readme.txt': strToU8('rien de special'),
  });
}

describe('plain archives', () => {
  it('is detected as an archive rather than a document package', () => {
    expect(detectFormat(makeArchive())).toBe('zip');
  });

  it('reports findings from documents inside it, with the member path', async () => {
    const { findings } = await inspectFile(makeArchive());
    const author = find(findings, 'Author');
    expect(author?.value).toBe('Lotfi Zakaria');
    expect(author?.location).toContain('export/deck.pptx');
  });

  it('reports front matter from a Markdown member', async () => {
    const { findings } = await inspectFile(makeArchive());
    expect(find(findings, 'Generated by')?.value).toBe('claude-opus');
  });

  it('finds a credential in a member no parser claims', async () => {
    const { findings } = await inspectFile(makeArchive());
    const credential = findings.find((f) => f.label.includes('Anthropic API key'));
    expect(credential?.location).toContain('.env');
    expect(credential?.value).not.toContain('DDDD');
  });

  it('reports absolute paths preserved in member names', async () => {
    const { findings } = await inspectFile(makeArchive());
    expect(find(findings, 'Absolute paths preserved in the archive')?.value).toContain('lotfi');
  });

  it('says the report is an aggregate', async () => {
    expect((await inspectFile(makeArchive())).notes.map((n) => n.code)).toContain('scope:archive');
  });

  it('refuses to rewrite an archive rather than repacking it silently', async () => {
    // Repacking would change compression, ordering and timestamps of every
    // member; redacting the files individually is the honest workflow.
    await expect(redactFile(makeArchive())).rejects.toBeInstanceOf(UnsupportedFormatError);
  });

  it('still handles a real document package as a document', async () => {
    const pptx = zipSync({
      '[Content_Types].xml': strToU8('<Types/>'),
      'ppt/presentation.xml': strToU8('<p:presentation/>'),
    });
    expect((await inspectFile(pptx)).format).toBe('pptx');
  });
});

/* ------------------------------------------------------------------ exposure */

describe('statistical watermark exposure', () => {
  it('estimates tokens as a range rather than a false precision', () => {
    const estimate = estimateTokens('a'.repeat(1000));
    expect(estimate.low).toBeLessThan(estimate.high);
    expect(estimate.characters).toBe(1000);
  });

  it('calls a short passage too short to conclude anything from', () => {
    expect(exposure('Bonjour, voici un texte court.').band).toBe('too-short');
  });

  it('calls a mid-length passage uncertain', () => {
    expect(exposure('mot '.repeat(400)).band).toBe('uncertain');
  });

  it('calls a long passage ample', () => {
    expect(exposure('mot '.repeat(2000)).band).toBe('ample');
  });

  it('judges on the lower bound, so the band is never overstated', () => {
    const report = exposure('mot '.repeat(400));
    expect(report.low).toBeLessThan(800);
    expect(report.band).not.toBe('ample');
  });

  it('never returns a verdict field, because no verdict is possible', () => {
    expect(Object.keys(exposure('texte'))).toEqual(
      expect.not.arrayContaining(['watermarked', 'detected', 'verdict', 'confidence']),
    );
  });
});

describe('redaction is measured, not asserted', () => {
  it('removes custom /Info keys, not only the standard ones', async () => {
    const { PDFDocument, PDFName, PDFString } = await import('pdf-lib');
    const pdf = await PDFDocument.create();
    pdf.addPage([200, 200]).drawText('contenu');
    pdf.setAuthor('Lotfi Zakaria');
    const info = pdf.context.lookup(pdf.context.trailerInfo.Info) as unknown as {
      set(k: unknown, v: unknown): void;
    };
    info.set(PDFName.of('GeneratedBy'), PDFString.of('claude-opus-5'));
    info.set(PDFName.of('SessionId'), PDFString.of('session_01ABCdef99'));

    const redacted = await redactFile(await pdf.save());
    const after = await inspectFile(redacted.data!);
    expect(after.findings.filter((f) => !isStructuralFinding(f))).toEqual([]);
  });

  it('names what survived instead of implying a clean file', async () => {
    const { PDFDocument } = await import('pdf-lib');
    const pdf = await PDFDocument.create();
    // A secret in the page text cannot be removed without rewriting the page.
    pdf.addPage([400, 300]).drawText(`Contact: sk-ant-api03-${'A'.repeat(40)}`, { size: 8 });
    pdf.setAuthor('Lotfi Zakaria');

    const redacted = await redactFile(await pdf.save());
    const kept = redacted.notes.find((n) => n.code === 'kept:in-content');
    expect(kept?.detail).toContain('Anthropic API key');

    // And it really does survive, which is why saying so matters.
    const after = await inspectFile(redacted.data!);
    expect(after.findings.filter((f) => !isStructuralFinding(f)).map((f) => f.label)).toEqual([
      'Credential left in file: Anthropic API key',
    ]);
  });

  it('stays quiet when nothing survived', async () => {
    const { PDFDocument } = await import('pdf-lib');
    const pdf = await PDFDocument.create();
    pdf.addPage([200, 200]).drawText('contenu ordinaire');
    pdf.setAuthor('Lotfi Zakaria');

    const redacted = await redactFile(await pdf.save());
    expect(redacted.notes.map((n) => n.code)).not.toContain('kept:in-content');
  });
});

describe('C2PA claim generator', () => {
  it('reads the tool a manifest credits, from XMP attribute syntax', async () => {
    const { readXmpClaimGenerator: readClaimGenerator } = await import('../src/core/c2pa.js');
    expect(readClaimGenerator('<x c2pa:claim_generator="claude/1.0 export/2.3"/>')).toBe(
      'claude/1.0 export/2.3',
    );
  });

  it('reads a binary manifest through its structure, not by scraping strings', async () => {
    const { readManifest } = await import('../src/core/c2pa.js');
    const { readFile } = await import('node:fs/promises');
    const jpeg = new Uint8Array(await readFile(new URL('./fixtures/signed.jpg', import.meta.url)));
    // Locate the APP11 segment carrying the JUMBF manifest.
    let segment: Uint8Array | undefined;
    for (let i = 2; i + 4 < jpeg.length; ) {
      if (jpeg[i] !== 0xff) break;
      const marker = (jpeg[i]! << 8) | jpeg[i + 1]!;
      if (marker === 0xffda) break;
      const length = (jpeg[i + 2]! << 8) | jpeg[i + 3]!;
      if (marker === 0xffeb) {
        segment = jpeg.subarray(i + 4, i + 2 + length);
        break;
      }
      i += 2 + length;
    }
    const summary = readManifest(segment!);
    expect(summary?.generator).toBe('make_test_images/0.33.1 c2pa-rs/0.33.1');
    expect(summary?.generatorInfo?.[0]).toEqual({ name: 'make_test_images', version: '0.33.1' });
    expect(summary?.algorithm).toBe('sha256');
    expect(summary?.assertions.length).toBeGreaterThan(0);
  });

  it('returns nothing when the manifest names no generator', async () => {
    const { readXmpClaimGenerator: readClaimGenerator } = await import('../src/core/c2pa.js');
    expect(readClaimGenerator('<x c2pa:something="else"/>')).toBeUndefined();
  });

  it('marks the credited tool as asserted rather than verified', async () => {
    const { describeC2pa } = await import('../src/core/c2pa.js');
    const findings = describeC2pa('<x c2pa:claim_generator="claude/1.0"/>', '/Metadata');
    const presence = findings.find((f) => f.label === 'C2PA content credentials');
    const credited = findings.find((f) => f.label === 'Tool credited by the C2PA manifest');

    // Presence is a fact about the bytes; the credit is the producer's word,
    // since nothing here walks the certificate chain.
    expect(presence?.confidence).toBe('confirmed');
    expect(credited?.confidence).toBe('probable');
    expect(credited?.value).toContain('signature not verified');
  });
});

describe('custom properties carry their values, not just their names', () => {
  const zip = (parts: Record<string, Uint8Array>) => zipSync(parts);

  it('reports each Office custom property with its value', async () => {
    const custom =
      '<Properties xmlns:vt="v">' +
      '<property name="Model" pid="2"><vt:lpwstr>claude-opus-5</vt:lpwstr></property>' +
      '<property name="RunId" pid="3"><vt:lpwstr>session_01ABCdef99</vt:lpwstr></property>' +
      '</Properties>';
    const { findings } = await inspectFile(
      zip({
        '[Content_Types].xml': strToU8('<Types/>'),
        'docProps/custom.xml': strToU8(custom),
        'word/document.xml': strToU8('<w:document><w:body/></w:document>'),
      }),
    );
    expect(find(findings, 'Custom property: Model')?.value).toBe('claude-opus-5');
    expect(find(findings, 'Custom property: RunId')?.value).toBe('session_01ABCdef99');
  });

  it('lets the fingerprint pass derive the model from that value', async () => {
    // A key called "Model" says nothing; only its value names the model, which
    // is the whole reason the value has to be reported.
    const custom =
      '<Properties xmlns:vt="v"><property name="Model" pid="2"><vt:lpwstr>claude-opus-5</vt:lpwstr></property></Properties>';
    const { findings } = await inspectFile(
      zip({
        '[Content_Types].xml': strToU8('<Types/>'),
        'docProps/custom.xml': strToU8(custom),
        'word/document.xml': strToU8('<w:document><w:body/></w:document>'),
      }),
    );
    expect(find(findings, 'Model identifier')?.value).toContain('claude-opus-5');
  });

  it('reports OpenDocument user-defined properties with their values', async () => {
    const meta =
      '<office:document-meta xmlns:office="o" xmlns:meta="m"><office:meta>' +
      '<meta:user-defined meta:name="Model">claude-opus-5</meta:user-defined>' +
      '</office:meta></office:document-meta>';
    const { findings } = await inspectFile(
      zip({
        mimetype: strToU8('application/vnd.oasis.opendocument.text'),
        'meta.xml': strToU8(meta),
        'content.xml': strToU8('<office:document-content/>'),
      }),
    );
    expect(find(findings, 'User-defined property: Model')?.value).toBe('claude-opus-5');
    expect(find(findings, 'Model identifier')?.value).toContain('claude-opus-5');
  });

  it('still removes them on redaction', async () => {
    const custom =
      '<Properties xmlns:vt="v"><property name="Model" pid="2"><vt:lpwstr>claude-opus-5</vt:lpwstr></property></Properties>';
    const redacted = await redactFile(
      zip({
        '[Content_Types].xml': strToU8('<Types/>'),
        'docProps/custom.xml': strToU8(custom),
        'word/document.xml': strToU8('<w:document><w:body/></w:document>'),
      }),
    );
    expect((await inspectFile(redacted.data!)).findings).toEqual([]);
  });

  it('reads the manifest an SVG carries, like any other container', async () => {
    const svg =
      '<svg xmlns="http://www.w3.org/2000/svg"><metadata>' +
      '<rdf:Description c2pa:claim_generator="claude/1.0"/></metadata></svg>';
    const { findings } = await inspectFile(new TextEncoder().encode(svg));
    const credited = find(findings, 'Tool credited by the C2PA manifest');
    expect(credited?.value).toContain('claude/1.0');
    expect(credited?.value).toContain('signature not verified');
  });
});

describe('CLI banner', () => {
  const plain = (t: string) => t;

  it('draws the mark with box-drawing characters when the terminal can show them', async () => {
    const { banner } = await import('../src/cli/logo.js');
    const rows = banner({ unicode: true, paint: plain, lines: [] }).split('\n');
    expect(rows[0]).toContain('╭');
    expect(rows.at(-1)).toContain('╯');
  });

  it('falls back to ASCII, since a legacy console renders the other as mojibake', async () => {
    const { banner } = await import('../src/cli/logo.js');
    const art = banner({ unicode: false, paint: plain, lines: [] });
    expect(art).not.toMatch(/[^\x00-\x7f]/);
    expect(art).toContain('+-------+');
  });

  it('keeps the text column aligned across both transcriptions', async () => {
    const { banner } = await import('../src/cli/logo.js');
    const lines = ['cirta'];
    const column = (unicode: boolean) =>
      banner({ unicode, paint: plain, lines }).split('\n')[0]!.indexOf('cirta');
    expect(column(true)).toBe(column(false));
  });

  it('pads short art or short text so neither truncates the other', async () => {
    const { banner } = await import('../src/cli/logo.js');
    const many = ['a', 'b', 'c', 'd', 'e', 'f'];
    expect(banner({ unicode: true, paint: plain, lines: many }).split('\n')).toHaveLength(6);
    expect(banner({ unicode: true, paint: plain, lines: ['a'] }).split('\n')).toHaveLength(4);
  });

  it('leaves no trailing whitespace on rows without text', async () => {
    const { banner } = await import('../src/cli/logo.js');
    for (const row of banner({ unicode: true, paint: plain, lines: ['a'] }).split('\n')) {
      expect(row).toBe(row.trimEnd());
    }
  });
});
