import { describe, it, expect } from 'vitest';
import { emailHeaders, stripToolHeaders, inspectPlainText, provenance } from '../src/core/index.js';

const find = (text: string, label: string) =>
  emailHeaders(text).find((f) => f.label === label);

const GENERATED = `From: Lotfi Zakaria <lotfixazk@gmail.com>
To: direction@example.fr
Subject: Proposition d'accompagnement
Message-ID: <a3f9c2e1-claude-opus-5@assistant.local>
X-Mailer: Claude Desktop 1.4.2
User-Agent: anthropic-sdk-python/0.34.0
X-Generated-By: claude-opus-5
Date: Thu, 14 Aug 2026 09:12:00 +0200

Bonjour,

Le corps du message.
`;

describe('mail headers', () => {
  it('names the software that composed the message', () => {
    expect(find(GENERATED, 'Mail client')?.value).toBe('Claude Desktop 1.4.2');
    expect(find(GENERATED, 'Composing agent')?.value).toBe('anthropic-sdk-python/0.34.0');
    expect(find(GENERATED, 'Generated by')?.value).toBe('claude-opus-5');
  });

  it('reports an X- header it has never seen, since the space is open by design', () => {
    const withCustom = GENERATED.replace('X-Mailer:', 'X-Pipeline-Run: build-7742\nX-Mailer:');
    expect(find(withCustom, 'Non-standard header: x-pipeline-run')?.value).toBe('build-7742');
  });

  it('joins a folded continuation line back onto its field', () => {
    const folded = GENERATED.replace(
      'User-Agent: anthropic-sdk-python/0.34.0',
      'User-Agent: anthropic-sdk-python/0.34.0\n  (Python 3.12; Linux)',
    );
    expect(find(folded, 'Composing agent')?.value).toBe(
      'anthropic-sdk-python/0.34.0 (Python 3.12; Linux)',
    );
  });

  it('numbers each relay so a routing chain stays readable', () => {
    const routed = GENERATED.replace(
      'From:',
      'Received: from a.example.fr\nReceived: from b.example.fr\nFrom:',
    );
    expect(find(routed, 'Relay hop')?.value).toContain('a.example.fr');
    expect(find(routed, 'Relay hop 2')?.value).toContain('b.example.fr');
  });

  it('leaves Subject, To and Date alone — they are the message, not metadata', () => {
    const labels = emailHeaders(GENERATED).map((f) => f.label);
    expect(labels).not.toContain('Subject');
    expect(labels).not.toContain('Date');
  });
});

describe('mail headers are not claimed where there are none', () => {
  it('ignores prose that happens to have a colon at the start of a line', () => {
    const memo = `Objet: refonte du portail
Contexte: le prestataire a livré en retard.

Trois points à trancher lundi.`;
    expect(emailHeaders(memo)).toEqual([]);
  });

  it('ignores a form with two field-shaped lines and no anchor', () => {
    const form = `Nom: Lotfi Zakaria
Fonction: architecte
Service: cybersécurité

Signature:`;
    expect(emailHeaders(form)).toEqual([]);
  });

  it('ignores YAML, which is field-shaped from top to bottom', () => {
    const yaml = `name: cirta
version: 0.1.0
license: MIT

# commentaire`;
    expect(emailHeaders(yaml)).toEqual([]);
  });
});

describe('cleaning a mail draft', () => {
  it('removes the headers that name a tool', () => {
    const { text, removed } = stripToolHeaders(GENERATED);
    expect(removed.map((n) => n.toLowerCase())).toEqual(['x-mailer', 'user-agent', 'x-generated-by']);
    expect(text).not.toContain('Claude Desktop');
    expect(text).not.toContain('anthropic-sdk-python');
  });

  it('keeps the message and its own headers', () => {
    const { text } = stripToolHeaders(GENERATED);
    expect(text).toContain('From: Lotfi Zakaria');
    expect(text).toContain("Subject: Proposition d'accompagnement");
    expect(text).toContain('Le corps du message.');
  });

  it('takes the folded continuation with the field it belongs to', () => {
    const folded = GENERATED.replace(
      'User-Agent: anthropic-sdk-python/0.34.0',
      'User-Agent: anthropic-sdk-python/0.34.0\n  (Python 3.12; Linux)',
    );
    expect(stripToolHeaders(folded).text).not.toContain('Python 3.12');
  });

  it('removes the line rather than emptying it, leaving an ordinary shape', () => {
    // A message with `X-Mailer:` present and blank is not one any client sends.
    expect(stripToolHeaders(GENERATED).text).not.toMatch(/^X-Mailer:\s*$/m);
  });

  it('does nothing to a text that is not a message', () => {
    const prose = 'Objet: refonte\n\nTrois points à trancher.';
    expect(stripToolHeaders(prose)).toEqual({ text: prose, removed: [] });
  });
});

describe('plain text gets the same provenance reading as a container', () => {
  it('names the assistant from a mail header', () => {
    const result = provenance(inspectPlainText(GENERATED));
    expect(result.attributed).toBe(true);
    expect(result.tools.join(' ')).toContain('Claude');
  });

  it('finds a path and a session identifier written into the body', () => {
    const draft = `Bonjour,\n\nVoici la note.\n\n--\nGénéré depuis /home/lotfi/.cache/session_01ABCdef99/note.txt\n`;
    const labels = inspectPlainText(draft).map((f) => f.label);
    expect(labels).toContain('Linux account');
    expect(labels).toContain('Session identifier');
  });

  it('does not accuse someone writing about an assistant', () => {
    // The single most important control in this file. A person comparing
    // vendors in an email has not written that email with them.
    const human = `From: Lotfi Zakaria <lotfixazk@gmail.com>
To: equipe@example.fr
Subject: Retour sur les assistants
Date: Thu, 14 Aug 2026 09:12:00 +0200

J'ai comparé Claude d'Anthropic, ChatGPT d'OpenAI et Gemini cette semaine.
Claude s'en sort mieux sur les documents longs. Je fais un tableau lundi.`;
    const result = provenance(inspectPlainText(human));
    expect(result.attributed).toBe(false);
    expect(result.tools).toEqual([]);
  });
});
