import { describe, it, expect } from 'vitest';
import { unzipSync, zipSync, strToU8, strFromU8 } from 'fflate';
import { inspectFile, redactFile, detectFormat, isStructuralFinding, type Finding } from '../src/core/index.js';

const encode = (text: string) => new TextEncoder().encode(text);
const decode = (data: Uint8Array) => new TextDecoder().decode(data);
const find = (findings: Finding[], label: string) => findings.find((f) => f.label === label);

/* -------------------------------------------------------------------- SVG */

const SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generator: Adobe Illustrator 28.0.0, SVG Export Plug-In -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" inkscape:version="1.3" width="100" height="100">
  <title>Schéma réseau interne</title>
  <metadata><rdf:RDF xmlns:rdf="x"><dc:creator>Lotfi Zakaria</dc:creator></rdf:RDF></metadata>
  <rect width="100" height="100" fill="red"/>
</svg>`;

describe('SVG', () => {
  it('is detected from its root element', () => {
    expect(detectFormat(encode(SVG))).toBe('svg');
  });

  it('reports the metadata block, the editor namespace and the generator comment', async () => {
    const { findings, format } = await inspectFile(encode(SVG));
    expect(format).toBe('svg');
    expect(find(findings, 'SVG metadata block')).toBeDefined();
    expect(find(findings, 'Editor namespace')?.value).toBe('inkscape');
    expect(find(findings, 'Generator comment')?.value).toContain('Adobe Illustrator');
  });

  it('reports the accessibility title as probable rather than confirmed', async () => {
    const { findings } = await inspectFile(encode(SVG));
    expect(find(findings, 'SVG title (accessibility)')?.confidence).toBe('probable');
  });

  it('removes metadata, editor attributes and generator comments', async () => {
    const cleaned = decode((await redactFile(encode(SVG))).data!);
    expect(cleaned).not.toContain('<metadata>');
    expect(cleaned).not.toContain('Lotfi Zakaria');
    expect(cleaned).not.toContain('inkscape');
    expect(cleaned).not.toContain('Adobe Illustrator');
  });

  it('keeps the drawing and the accessibility title', async () => {
    // <title> is what a screen reader announces; removing it is a regression.
    const cleaned = decode((await redactFile(encode(SVG))).data!);
    expect(cleaned).toContain('<rect');
    expect(cleaned).toContain('Schéma réseau interne');
    expect(cleaned).toContain('<svg');
  });
});

/* ------------------------------------------------------------------- HTML */

const HTML = `<!doctype html>
<html><head>
<meta charset="utf-8">
<meta name="generator" content="Claude Code export 1.0">
<meta name="author" content="Lotfi Zakaria">
<meta name="viewport" content="width=device-width">
<!-- Generated by build-pipeline on /home/lotfi/site -->
<script type="application/ld+json">{"@type":"Article","author":"Lotfi"}</script>
</head><body><p>Contenu</p></body></html>`;

describe('HTML', () => {
  it('is detected from its doctype', () => {
    expect(detectFormat(encode(HTML))).toBe('html');
  });

  it('reports generator and author meta tags', async () => {
    const { findings } = await inspectFile(encode(HTML));
    expect(find(findings, 'Generator meta tag')?.value).toBe('Claude Code export 1.0');
    expect(find(findings, 'Author meta tag')?.value).toBe('Lotfi Zakaria');
  });

  it('derives the assistant and the account from those values', async () => {
    const { findings } = await inspectFile(encode(HTML));
    expect(find(findings, 'Assistant or agent named in metadata')?.value).toContain('Claude');
    expect(find(findings, 'Linux account')?.value).toBe('lotfi');
  });

  it('removes the identifying meta tags and generator comment', async () => {
    const cleaned = decode((await redactFile(encode(HTML))).data!);
    expect(cleaned).not.toContain('Claude Code export');
    expect(cleaned).not.toContain('Lotfi Zakaria');
    expect(cleaned).not.toContain('build-pipeline');
  });

  it('keeps the body, the charset and the viewport', async () => {
    const cleaned = decode((await redactFile(encode(HTML))).data!);
    expect(cleaned).toContain('<p>Contenu</p>');
    expect(cleaned).toContain('charset');
    expect(cleaned).toContain('viewport');
  });

  it('reports JSON-LD but leaves it in place, since it is indexed content', async () => {
    const { findings } = await inspectFile(encode(HTML));
    expect(find(findings, 'JSON-LD structured data')).toBeDefined();
    expect(decode((await redactFile(encode(HTML))).data!)).toContain('application/ld+json');
  });
});

/* --------------------------------------------------------------- Markdown */

const MARKDOWN = `---
title: Rapport trimestriel
author: Lotfi Zakaria
generated_by: claude-opus
session: session_01ABCdef99
tags: [interne, q3]
---

# Rapport

Contenu du rapport.
`;

describe('Markdown front matter', () => {
  it('is detected from its front matter', () => {
    expect(detectFormat(encode(MARKDOWN))).toBe('markdown');
  });

  it('falls back to the extension hint when there is no front matter', () => {
    expect(detectFormat(encode('# Titre\n\nTexte.'), 'markdown')).toBe('markdown');
    // Without the hint it is no longer refused: bytes that decode as text but
    // match no markup still get the character-level pass, which is the whole
    // point of routing plain text and source files.
    expect(detectFormat(encode('# Titre\n\nTexte.'))).toBe('text');
  });

  it('reports author, generator and session keys', async () => {
    const { findings } = await inspectFile(encode(MARKDOWN));
    expect(find(findings, 'Author')?.value).toBe('Lotfi Zakaria');
    expect(find(findings, 'Generated by')?.value).toBe('claude-opus');
    expect(find(findings, 'Session')?.value).toBe('session_01ABCdef99');
  });

  it('names the assistant from the generator key', async () => {
    const { findings } = await inspectFile(encode(MARKDOWN));
    expect(find(findings, 'Assistant or agent named in metadata')?.value).toContain('Claude');
  });

  it('removes only the identifying keys', async () => {
    const cleaned = decode((await redactFile(encode(MARKDOWN))).data!);
    expect(cleaned).not.toContain('Lotfi Zakaria');
    expect(cleaned).not.toContain('claude-opus');
    expect(cleaned).not.toContain('session_01ABCdef99');
    expect(cleaned).toContain('title: Rapport trimestriel');
    expect(cleaned).toContain('tags: [interne, q3]');
  });

  it('keeps the body untouched', async () => {
    const cleaned = decode((await redactFile(encode(MARKDOWN))).data!);
    expect(cleaned).toContain('# Rapport');
    expect(cleaned).toContain('Contenu du rapport.');
  });

  it('drops the delimiters when nothing is left inside them', async () => {
    const only = '---\nauthor: Lotfi\n---\n\n# Titre\n';
    const cleaned = decode((await redactFile(encode(only))).data!);
    expect(cleaned.trimStart().startsWith('#')).toBe(true);
    expect(cleaned).not.toContain('---');
  });
});

/* ------------------------------------------------------------ OpenDocument */

function makeOdt(): Uint8Array {
  const meta = `<?xml version="1.0" encoding="UTF-8"?>
<office:document-meta xmlns:office="o" xmlns:meta="m" xmlns:dc="d">
<office:meta><meta:generator>LibreOffice/24.8.0.3$Linux_X86_64</meta:generator><meta:initial-creator>Lotfi Zakaria</meta:initial-creator><dc:creator>lotfi.z</dc:creator><meta:creation-date>2026-08-01T09:12:00</meta:creation-date><meta:editing-cycles>7</meta:editing-cycles><meta:user-defined meta:name="Classification">Confidentiel</meta:user-defined></office:meta></office:document-meta>`;
  return zipSync({
    mimetype: strToU8('application/vnd.oasis.opendocument.text'),
    'meta.xml': strToU8(meta),
    'content.xml': strToU8('<office:document-content/>'),
    'Thumbnails/thumbnail.png': new Uint8Array([0x89, 0x50, 0x4e, 0x47]),
  });
}

describe('OpenDocument', () => {
  it('is distinguished from OOXML by its mimetype entry', async () => {
    expect((await inspectFile(makeOdt())).format).toBe('odt');
  });

  it('reports the initial creator, which survives a changed author', async () => {
    const { findings } = await inspectFile(makeOdt());
    expect(find(findings, 'Initial author')?.value).toBe('Lotfi Zakaria');
    expect(find(findings, 'Last modified by')?.value).toBe('lotfi.z');
  });

  it('reports the generator as informational and user-defined keys as confirmed', async () => {
    const { findings } = await inspectFile(makeOdt());
    expect(find(findings, 'Producing application')?.confidence).toBe('informational');
    expect(find(findings, 'User-defined property: Classification')?.value).toBe('Confidentiel');
  });

  it('leaves no metadata behind after redaction', async () => {
    const redacted = await redactFile(makeOdt());
    const after = await inspectFile(redacted.data!);
    expect(after.findings.filter((f) => !isStructuralFinding(f))).toEqual([]);
  });

  it('removes the generator rather than blanking it, leaving no scrub trace', async () => {
    const parts = unzipSync((await redactFile(makeOdt())).data!);
    const meta = strFromU8(parts['meta.xml']!);
    // An empty <meta:generator/> is a shape no application writes, so blanking
    // would trade one mark for another.
    expect(meta).not.toContain('<meta:generator');
    expect(meta).not.toContain('<meta:initial-creator');
  });

  it('keeps mimetype as the first entry, as the package spec requires', async () => {
    const parts = unzipSync((await redactFile(makeOdt())).data!);
    expect(Object.keys(parts)[0]).toBe('mimetype');
    expect(strFromU8(parts['mimetype']!)).toBe('application/vnd.oasis.opendocument.text');
  });

  it('drops the thumbnail and keeps the content', async () => {
    const parts = unzipSync((await redactFile(makeOdt())).data!);
    expect(Object.keys(parts)).not.toContain('Thumbnails/thumbnail.png');
    expect(Object.keys(parts)).toContain('content.xml');
  });
});

/* ------------------------------------------------------- images autonomes */

const latin1 = (t: string) => Uint8Array.from([...t].map((c) => c.charCodeAt(0)));

function jpegWithC2pa(): Uint8Array {
  // APP11 carrying a JUMBF box, which is where C2PA stores its manifest.
  const body = Uint8Array.from([...latin1('JP'), 0, 1, 0, 0, 0, 1, ...latin1('jumbc2pa-manifest')]);
  const length = body.length + 2;
  return Uint8Array.from([
    0xff, 0xd8,
    0xff, 0xeb, length >> 8, length & 0xff, ...body,
    0xff, 0xda, 0x00, 0x08, 1, 1, 0, 0, 0, 0,
    0x12, 0x34,
    0xff, 0xd9,
  ]);
}

function pngChunk(type: string, body: Uint8Array): Uint8Array {
  const n = body.length;
  return Uint8Array.from([
    (n >>> 24) & 0xff, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff,
    ...latin1(type), ...body, 0, 0, 0, 0,
  ]);
}

function pngWithC2pa(): Uint8Array {
  return Uint8Array.from([
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
    ...pngChunk('IHDR', new Uint8Array(13)),
    ...pngChunk('caBX', latin1('c2pa manifest bytes')),
    ...pngChunk('IDAT', new Uint8Array([1, 2, 3])),
    ...pngChunk('IEND', new Uint8Array(0)),
  ]);
}

describe('standalone images', () => {
  it('accepts a JPEG as a top-level file', async () => {
    expect((await inspectFile(jpegWithC2pa())).format).toBe('jpeg');
  });

  it('accepts a PNG as a top-level file', async () => {
    expect((await inspectFile(pngWithC2pa())).format).toBe('png');
  });

  it('reports a C2PA manifest carried in a JPEG APP11/JUMBF segment', async () => {
    const { findings } = await inspectFile(jpegWithC2pa());
    const c2pa = find(findings, 'C2PA content credentials');
    expect(c2pa?.confidence).toBe('confirmed');
    expect(c2pa?.affectsVerifiability).toBe(true);
  });

  it('reports a C2PA manifest carried in a PNG caBX chunk', async () => {
    const { findings } = await inspectFile(pngWithC2pa());
    expect(find(findings, 'C2PA content credentials')?.affectsVerifiability).toBe(true);
  });

  it('removes the manifest and says the file is no longer verifiable', async () => {
    for (const image of [jpegWithC2pa(), pngWithC2pa()]) {
      const redacted = await redactFile(image);
      expect((await inspectFile(redacted.data!)).findings).toEqual([]);
      expect(redacted.notes.map((n) => n.code)).toContain('removed:c2pa');
    }
  });

  it('states that the pixels were not analysed', async () => {
    const { notes } = await inspectFile(pngWithC2pa());
    expect(notes.map((n) => n.code)).toContain('scope:image-metadata-only');
  });

  it('keeps the image data when stripping a JPEG manifest', async () => {
    const redacted = (await redactFile(jpegWithC2pa())).data!;
    expect([...redacted.subarray(0, 2)]).toEqual([0xff, 0xd8]);
    expect([...redacted.subarray(-2)]).toEqual([0xff, 0xd9]);
  });

  it('leaves JPEG APP11 alone when it is not JUMBF', async () => {
    // The same marker carries JPEG XT extension data, which is picture
    // information rather than provenance.
    const body = latin1('XT-extension-payload');
    const length = body.length + 2;
    const jpegXt = Uint8Array.from([
      0xff, 0xd8,
      0xff, 0xeb, length >> 8, length & 0xff, ...body,
      0xff, 0xda, 0x00, 0x08, 1, 1, 0, 0, 0, 0, 0x12,
      0xff, 0xd9,
    ]);
    expect((await inspectFile(jpegXt)).findings).toEqual([]);
    expect((await redactFile(jpegXt)).data).toEqual(jpegXt);
  });
});

/* -------------------------------------------- texte du corps des documents */

const ZWSP = '​';
const NBSP = ' ';
const ZWJ = '‍';
const tagEncoded = (payload: string) =>
  [...payload].map((c) => String.fromCodePoint(0xe0000 + c.charCodeAt(0))).join('');

function makeDocxBody(text: string): Uint8Array {
  return zipSync({
    '[Content_Types].xml': strToU8('<Types/>'),
    'word/document.xml': strToU8(
      `<w:document><w:body><w:p><w:r><w:t>${text}</w:t></w:r></w:p></w:body></w:document>`,
    ),
  });
}

const docxText = (data: Uint8Array) =>
  /<w:t>([^<]*)<\/w:t>/.exec(strFromU8(unzipSync(data)['word/document.xml']!))?.[1] ?? '';

describe('invisible characters inside document bodies', () => {
  it('reports them with the part they came from', async () => {
    const { findings } = await inspectFile(makeDocxBody(`Bonjour,${ZWSP}${ZWSP} voici.`));
    const zwsp = find(findings, 'zero-width space');
    expect(zwsp?.value).toBe('2 occurrences');
    expect(zwsp?.location).toContain('word/document.xml');
  });

  it('decodes a payload hidden in the body text', async () => {
    const { findings } = await inspectFile(makeDocxBody(`Rapport${tagEncoded('ID42')}.`));
    expect(find(findings, 'Hidden payload in document text')?.value).toContain('ID42');
  });

  it('sees a character escaped as a numeric reference', async () => {
    // &#x200B; is a zero-width space written the long way; missing it would
    // make the whole check trivial to sidestep.
    const { findings } = await inspectFile(makeDocxBody('Encod&#x200B;&#x200B;é.'));
    expect(find(findings, 'zero-width space')?.value).toBe('2 occurrences');
  });

  it('grades exotic whitespace below zero-width characters', async () => {
    const { findings } = await inspectFile(makeDocxBody(`le${NBSP}rapport${ZWSP}final`));
    expect(find(findings, 'no-break space')?.confidence).toBe('informational');
    expect(find(findings, 'zero-width space')?.confidence).toBe('confirmed');
  });

  it('removes them on redaction and leaves nothing behind', async () => {
    const redacted = await redactFile(makeDocxBody(`Bonjour,${ZWSP}${ZWSP} voici${tagEncoded('X9')}.`));
    expect((await inspectFile(redacted.data!)).findings).toEqual([]);
    expect(docxText(redacted.data!)).toBe('Bonjour, voici.');
  });

  it('keeps exotic whitespace, which is typography rather than marking', async () => {
    // A no-break space before a colon is correct French typography. Normalising
    // it inside a formatted document degrades the document, so the body cleaner
    // reports it and leaves it, unlike the plain-text cleaner.
    const redacted = await redactFile(makeDocxBody(`Objet${NBSP}: le${NBSP}rapport`));
    expect(docxText(redacted.data!)).toBe(`Objet${NBSP}: le${NBSP}rapport`);
  });

  it('still removes zero-width characters sitting next to a no-break space', async () => {
    const redacted = await redactFile(makeDocxBody(`Objet${NBSP}:${ZWSP} suite`));
    expect(docxText(redacted.data!)).toBe(`Objet${NBSP}: suite`);
  });

  it('removes a numeric-reference escape rather than leaving the markup', async () => {
    const redacted = await redactFile(makeDocxBody('Encod&#x200B;é'));
    expect(strFromU8(unzipSync(redacted.data!)['word/document.xml']!)).not.toContain('&#x200B;');
    expect(docxText(redacted.data!)).toBe('Encodé');
  });

  it('preserves emoji joiners in the body', async () => {
    const developer = `\u{1F469}${ZWJ}\u{1F4BB}`;
    const redacted = await redactFile(makeDocxBody(`équipe ${developer} ok`));
    expect(docxText(redacted.data!)).toContain(developer);
  });

  it('never touches the XML structure', async () => {
    const redacted = await redactFile(makeDocxBody(`texte${ZWSP}`));
    const xml = strFromU8(unzipSync(redacted.data!)['word/document.xml']!);
    expect(xml.startsWith('<w:document>')).toBe(true);
    expect(xml.endsWith('</w:document>')).toBe(true);
    expect(xml).toContain('<w:body><w:p><w:r><w:t>');
  });

  it('ignores structural parts, where the same codepoints mean nothing', async () => {
    const docx = zipSync({
      '[Content_Types].xml': strToU8(`<Types><X>a${ZWSP}b</X></Types>`),
      'word/document.xml': strToU8('<w:document><w:body/></w:document>'),
    });
    expect((await inspectFile(docx)).findings).toEqual([]);
  });
});

describe('invisible characters in markup bodies', () => {
  const tagPayload = tagEncoded('ID42');

  it('finds them in Markdown', async () => {
    const { findings } = await inspectFile(
      encode(`# Titre\n\nBonjour,${ZWSP}${ZWSP} voici${tagPayload}.\n`),
      'markdown',
    );
    expect(find(findings, 'zero-width space')?.value).toBe('2 occurrences');
    expect(find(findings, 'Hidden payload in document text')?.value).toContain('ID42');
  });

  it('finds them in HTML text, not in the markup', async () => {
    const { findings } = await inspectFile(
      encode(`<!doctype html><html><body><p>Bonjour,${ZWSP}${ZWSP} voici.</p></body></html>`),
    );
    expect(find(findings, 'zero-width space')?.value).toBe('2 occurrences');
  });

  it('finds them in SVG text', async () => {
    const { findings } = await inspectFile(
      encode(`<svg xmlns="http://www.w3.org/2000/svg"><text>Bonjour${ZWSP}${ZWSP}</text></svg>`),
    );
    expect(find(findings, 'zero-width space')?.value).toBe('2 occurrences');
  });

  it('removes them from Markdown while keeping the prose', async () => {
    const redacted = await redactFile(
      encode(`# Titre\n\nBonjour,${ZWSP}${ZWSP} voici${tagPayload}.\n`),
      'markdown',
    );
    expect(decode(redacted.data!)).toBe('# Titre\n\nBonjour, voici.\n');
    expect((await inspectFile(redacted.data!, 'markdown')).findings).toEqual([]);
  });

  it('removes them from HTML without disturbing the tags', async () => {
    const redacted = await redactFile(
      encode(`<!doctype html><html><body><p>Bonjour,${ZWSP} voici.</p></body></html>`),
    );
    const cleaned = decode(redacted.data!);
    expect(cleaned).toContain('<p>Bonjour, voici.</p>');
    expect(cleaned).toContain('</body></html>');
  });

  it('keeps typographic spaces in markup bodies too', async () => {
    const redacted = await redactFile(encode(`Objet${NBSP}: le rapport\n`), 'markdown');
    expect(decode(redacted.data!)).toBe(`Objet${NBSP}: le rapport\n`);
  });

  it('does not list a kept typographic space as an unremoved survivor', async () => {
    // Informational findings are kept on purpose; naming them would bury the
    // survivors that genuinely could not be removed.
    const redacted = await redactFile(encode(`Objet${NBSP}: le rapport\n`), 'markdown');
    expect(redacted.notes.map((n) => n.code)).not.toContain('kept:in-content');
  });
});

describe('data-ai attributes', () => {
  const page = `<!doctype html><html><body>
  <p data-ai-generated="true" data-ai-model="claude">Un paragraphe.</p>
  <p>Un autre.</p>
  </body></html>`;

  it('reports them', async () => {
    const result = await inspectFile(encode(page), 'page.html');
    const finding = result.findings.find((f) => f.label === 'AI provenance data attributes');
    expect(finding?.confidence).toBe('confirmed');
    expect(finding?.value).toContain('2 attributes');
  });

  it('removes them and leaves the text alone', async () => {
    // Unlike JSON-LD, these change nothing a reader or a search engine sees.
    const cleaned = decode((await redactFile(encode(page), 'page.html')).data!);
    expect(cleaned).not.toContain('data-ai');
    expect(cleaned).toContain('Un paragraphe.');
    expect(cleaned).toContain('<p>Un autre.</p>');
  });
});
