import { describe, it, expect } from 'vitest';
import { unzipSync, zipSync, strToU8, strFromU8 } from 'fflate';
import { inspectFile, redactFile, detectFormat, type Finding } from '../src/core/index.js';

const encode = (text: string) => new TextEncoder().encode(text);
const decode = (data: Uint8Array) => new TextDecoder().decode(data);
const find = (findings: Finding[], label: string) => findings.find((f) => f.label === label);

/* -------------------------------------------------------------------- SVG */

const SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generator: Adobe Illustrator 28.0.0, SVG Export Plug-In -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" inkscape:version="1.3" width="100" height="100">
  <title>Schéma réseau interne</title>
  <metadata><rdf:RDF xmlns:rdf="x"><dc:creator>Lotfi Zakaria</dc:creator></rdf:RDF></metadata>
  <rect width="100" height="100" fill="red"/>
</svg>`;

describe('SVG', () => {
  it('is detected from its root element', () => {
    expect(detectFormat(encode(SVG))).toBe('svg');
  });

  it('reports the metadata block, the editor namespace and the generator comment', async () => {
    const { findings, format } = await inspectFile(encode(SVG));
    expect(format).toBe('svg');
    expect(find(findings, 'SVG metadata block')).toBeDefined();
    expect(find(findings, 'Editor namespace')?.value).toBe('inkscape');
    expect(find(findings, 'Generator comment')?.value).toContain('Adobe Illustrator');
  });

  it('reports the accessibility title as probable rather than confirmed', async () => {
    const { findings } = await inspectFile(encode(SVG));
    expect(find(findings, 'SVG title (accessibility)')?.confidence).toBe('probable');
  });

  it('removes metadata, editor attributes and generator comments', async () => {
    const cleaned = decode((await redactFile(encode(SVG))).data!);
    expect(cleaned).not.toContain('<metadata>');
    expect(cleaned).not.toContain('Lotfi Zakaria');
    expect(cleaned).not.toContain('inkscape');
    expect(cleaned).not.toContain('Adobe Illustrator');
  });

  it('keeps the drawing and the accessibility title', async () => {
    // <title> is what a screen reader announces; removing it is a regression.
    const cleaned = decode((await redactFile(encode(SVG))).data!);
    expect(cleaned).toContain('<rect');
    expect(cleaned).toContain('Schéma réseau interne');
    expect(cleaned).toContain('<svg');
  });
});

/* ------------------------------------------------------------------- HTML */

const HTML = `<!doctype html>
<html><head>
<meta charset="utf-8">
<meta name="generator" content="Claude Code export 1.0">
<meta name="author" content="Lotfi Zakaria">
<meta name="viewport" content="width=device-width">
<!-- Generated by build-pipeline on /home/lotfi/site -->
<script type="application/ld+json">{"@type":"Article","author":"Lotfi"}</script>
</head><body><p>Contenu</p></body></html>`;

describe('HTML', () => {
  it('is detected from its doctype', () => {
    expect(detectFormat(encode(HTML))).toBe('html');
  });

  it('reports generator and author meta tags', async () => {
    const { findings } = await inspectFile(encode(HTML));
    expect(find(findings, 'Generator meta tag')?.value).toBe('Claude Code export 1.0');
    expect(find(findings, 'Author meta tag')?.value).toBe('Lotfi Zakaria');
  });

  it('derives the assistant and the account from those values', async () => {
    const { findings } = await inspectFile(encode(HTML));
    expect(find(findings, 'Assistant or agent named in metadata')?.value).toContain('Claude');
    expect(find(findings, 'Linux account')?.value).toBe('lotfi');
  });

  it('removes the identifying meta tags and generator comment', async () => {
    const cleaned = decode((await redactFile(encode(HTML))).data!);
    expect(cleaned).not.toContain('Claude Code export');
    expect(cleaned).not.toContain('Lotfi Zakaria');
    expect(cleaned).not.toContain('build-pipeline');
  });

  it('keeps the body, the charset and the viewport', async () => {
    const cleaned = decode((await redactFile(encode(HTML))).data!);
    expect(cleaned).toContain('<p>Contenu</p>');
    expect(cleaned).toContain('charset');
    expect(cleaned).toContain('viewport');
  });

  it('reports JSON-LD but leaves it in place, since it is indexed content', async () => {
    const { findings } = await inspectFile(encode(HTML));
    expect(find(findings, 'JSON-LD structured data')).toBeDefined();
    expect(decode((await redactFile(encode(HTML))).data!)).toContain('application/ld+json');
  });
});

/* --------------------------------------------------------------- Markdown */

const MARKDOWN = `---
title: Rapport trimestriel
author: Lotfi Zakaria
generated_by: claude-opus
session: session_01ABCdef99
tags: [interne, q3]
---

# Rapport

Contenu du rapport.
`;

describe('Markdown front matter', () => {
  it('is detected from its front matter', () => {
    expect(detectFormat(encode(MARKDOWN))).toBe('markdown');
  });

  it('falls back to the extension hint when there is no front matter', () => {
    expect(detectFormat(encode('# Titre\n\nTexte.'), 'markdown')).toBe('markdown');
    expect(detectFormat(encode('# Titre\n\nTexte.'))).toBeUndefined();
  });

  it('reports author, generator and session keys', async () => {
    const { findings } = await inspectFile(encode(MARKDOWN));
    expect(find(findings, 'Author')?.value).toBe('Lotfi Zakaria');
    expect(find(findings, 'Generated by')?.value).toBe('claude-opus');
    expect(find(findings, 'Session')?.value).toBe('session_01ABCdef99');
  });

  it('names the assistant from the generator key', async () => {
    const { findings } = await inspectFile(encode(MARKDOWN));
    expect(find(findings, 'Assistant or agent named in metadata')?.value).toContain('Claude');
  });

  it('removes only the identifying keys', async () => {
    const cleaned = decode((await redactFile(encode(MARKDOWN))).data!);
    expect(cleaned).not.toContain('Lotfi Zakaria');
    expect(cleaned).not.toContain('claude-opus');
    expect(cleaned).not.toContain('session_01ABCdef99');
    expect(cleaned).toContain('title: Rapport trimestriel');
    expect(cleaned).toContain('tags: [interne, q3]');
  });

  it('keeps the body untouched', async () => {
    const cleaned = decode((await redactFile(encode(MARKDOWN))).data!);
    expect(cleaned).toContain('# Rapport');
    expect(cleaned).toContain('Contenu du rapport.');
  });

  it('drops the delimiters when nothing is left inside them', async () => {
    const only = '---\nauthor: Lotfi\n---\n\n# Titre\n';
    const cleaned = decode((await redactFile(encode(only))).data!);
    expect(cleaned.trimStart().startsWith('#')).toBe(true);
    expect(cleaned).not.toContain('---');
  });
});

/* ------------------------------------------------------------ OpenDocument */

function makeOdt(): Uint8Array {
  const meta = `<?xml version="1.0" encoding="UTF-8"?>
<office:document-meta xmlns:office="o" xmlns:meta="m" xmlns:dc="d">
<office:meta><meta:generator>LibreOffice/24.8.0.3$Linux_X86_64</meta:generator><meta:initial-creator>Lotfi Zakaria</meta:initial-creator><dc:creator>lotfi.z</dc:creator><meta:creation-date>2026-08-01T09:12:00</meta:creation-date><meta:editing-cycles>7</meta:editing-cycles><meta:user-defined meta:name="Classification">Confidentiel</meta:user-defined></office:meta></office:document-meta>`;
  return zipSync({
    mimetype: strToU8('application/vnd.oasis.opendocument.text'),
    'meta.xml': strToU8(meta),
    'content.xml': strToU8('<office:document-content/>'),
    'Thumbnails/thumbnail.png': new Uint8Array([0x89, 0x50, 0x4e, 0x47]),
  });
}

describe('OpenDocument', () => {
  it('is distinguished from OOXML by its mimetype entry', async () => {
    expect((await inspectFile(makeOdt())).format).toBe('odt');
  });

  it('reports the initial creator, which survives a changed author', async () => {
    const { findings } = await inspectFile(makeOdt());
    expect(find(findings, 'Initial author')?.value).toBe('Lotfi Zakaria');
    expect(find(findings, 'Last modified by')?.value).toBe('lotfi.z');
  });

  it('reports the generator as informational and user-defined keys as confirmed', async () => {
    const { findings } = await inspectFile(makeOdt());
    expect(find(findings, 'Producing application')?.confidence).toBe('informational');
    expect(find(findings, 'User-defined properties')?.value).toBe('Classification');
  });

  it('leaves no metadata behind after redaction', async () => {
    const redacted = await redactFile(makeOdt());
    expect((await inspectFile(redacted.data!)).findings).toEqual([]);
  });

  it('keeps mimetype as the first entry, as the package spec requires', async () => {
    const parts = unzipSync((await redactFile(makeOdt())).data!);
    expect(Object.keys(parts)[0]).toBe('mimetype');
    expect(strFromU8(parts['mimetype']!)).toBe('application/vnd.oasis.opendocument.text');
  });

  it('drops the thumbnail and keeps the content', async () => {
    const parts = unzipSync((await redactFile(makeOdt())).data!);
    expect(Object.keys(parts)).not.toContain('Thumbnails/thumbnail.png');
    expect(Object.keys(parts)).toContain('content.xml');
  });
});
