/**
 * The header block of a mail message, when the pasted text turns out to be one.
 *
 * This exists because of how the tool is actually used: a draft is generated,
 * then saved or exported, and what comes back is a `.eml`, a "show original"
 * dump, or a body pasted with its headers still attached. Those headers are the
 * most talkative metadata in this whole tool — a mail client writes its own
 * name into `X-Mailer` as a matter of course, an SDK writes itself into
 * `User-Agent`, and `Message-ID` routinely carries the hostname of the machine
 * that composed the message.
 *
 * Two decisions shape what follows.
 *
 * The first is that only a real header block counts. `Subject:` at the start of
 * a line is a shape ordinary prose produces by accident — a list of fields in a
 * document, a quoted excerpt, a form. Requiring several distinct headers, one
 * of which must be an address or a routing field, is what keeps this from
 * firing on a memo that happens to have a line beginning with `To:`.
 *
 * The second is that the values are reported and nothing more is inferred from
 * them here. `fingerprint()` already knows how to recognise an assistant, a
 * model name, a session identifier or a home directory inside a value, and it
 * runs over these findings like any other. Duplicating that judgement in this
 * module would mean maintaining it twice and having the two drift apart.
 */

import type { Finding, Confidence } from './types.js';

interface HeaderRule {
  /** Lowercase header name, matched exactly. */
  name: string;
  label: string;
  kind: Finding['kind'];
  confidence: Confidence;
}

/**
 * Headers worth reporting, and why each one earns its place.
 *
 * Deliberately not here: Subject, Date, To, Cc. They are the message — the
 * person wrote them and already knows what they say. Reporting them would bury
 * the four or five lines that actually reveal something.
 */
const HEADERS: HeaderRule[] = [
  // -- what composed the message ------------------------------------------
  { name: 'x-mailer', label: 'Mail client', kind: 'provenance', confidence: 'confirmed' },
  { name: 'user-agent', label: 'Composing agent', kind: 'provenance', confidence: 'confirmed' },
  { name: 'x-generated-by', label: 'Generated by', kind: 'provenance', confidence: 'confirmed' },
  { name: 'x-generator', label: 'Generated by', kind: 'provenance', confidence: 'confirmed' },
  { name: 'x-originating-client', label: 'Originating client', kind: 'provenance', confidence: 'confirmed' },
  { name: 'x-ai-generated', label: 'Declared as AI-generated', kind: 'provenance', confidence: 'confirmed' },

  // -- who and where -------------------------------------------------------
  { name: 'from', label: 'Sender', kind: 'identity', confidence: 'confirmed' },
  { name: 'reply-to', label: 'Reply-to address', kind: 'identity', confidence: 'confirmed' },
  { name: 'return-path', label: 'Return path', kind: 'identity', confidence: 'confirmed' },
  { name: 'sender', label: 'Envelope sender', kind: 'identity', confidence: 'confirmed' },
  { name: 'x-originating-ip', label: 'Originating IP address', kind: 'identity', confidence: 'confirmed' },
  { name: 'bcc', label: 'Blind carbon copy', kind: 'identity', confidence: 'confirmed' },

  // -- identifiers that outlive the message --------------------------------
  // A Message-ID's right-hand side is a hostname by convention, and clients
  // that generate it locally put the machine's name there.
  { name: 'message-id', label: 'Message identifier', kind: 'identity', confidence: 'probable' },
  { name: 'in-reply-to', label: 'In reply to', kind: 'identity', confidence: 'probable' },
  { name: 'references', label: 'Thread references', kind: 'identity', confidence: 'probable' },
  { name: 'thread-index', label: 'Thread index', kind: 'identity', confidence: 'probable' },
  { name: 'thread-topic', label: 'Thread topic', kind: 'identity', confidence: 'probable' },

  // -- the path the message took -------------------------------------------
  // Received lines name every relay, including the first one, which is often
  // the composing machine on a home network.
  { name: 'received', label: 'Relay hop', kind: 'identity', confidence: 'probable' },
  { name: 'x-forwarded-for', label: 'Forwarded for', kind: 'identity', confidence: 'probable' },
];

const BY_NAME = new Map(HEADERS.map((rule) => [rule.name, rule]));

/**
 * Fields whose presence makes a block a mail header rather than a coincidence.
 * At least one is required, on top of a count of distinct known headers.
 */
const ANCHORS = new Set(['from', 'to', 'received', 'message-id', 'return-path', 'date']);

/** Any RFC 5322 field name: printable ASCII except colon, then a colon. */
const FIELD = /^([!-9;-~]+):[ \t]*(.*)$/;

interface Header {
  name: string;
  value: string;
}

/**
 * Read the header block, stopping at the first blank line as the format
 * requires. Folded continuation lines — a leading space or tab — are joined
 * back onto the field they belong to, or a long `Received` chain would be read
 * as a dozen unparseable fragments.
 */
function parseBlock(text: string): Header[] | undefined {
  const headers: Header[] = [];
  const lines = text.split(/\r?\n/);

  for (const line of lines) {
    if (line.trim() === '') break;
    if (/^[ \t]/.test(line) && headers.length) {
      headers[headers.length - 1]!.value += ' ' + line.trim();
      continue;
    }
    const match = FIELD.exec(line);
    // A line that is not a field ends the block: in a real message the headers
    // run without interruption until the blank line.
    if (!match) return headers.length ? headers : undefined;
    headers.push({ name: match[1]!.toLowerCase(), value: match[2]!.trim() });
  }

  return headers.length ? headers : undefined;
}

/**
 * Findings from a mail header block, or nothing if the text is not one.
 *
 * The threshold is three distinct recognised headers including an anchor. Two
 * would fire on a form with `From:` and `Date:` lines; three with an anchor has
 * not produced a false positive on any ordinary prose tried against it.
 */
export function emailHeaders(text: string): Finding[] {
  const headers = parseBlock(text);
  if (!headers) return [];

  const names = new Set(headers.map((h) => h.name));
  const known = [...names].filter((name) => BY_NAME.has(name) || ANCHORS.has(name));
  if (known.length < 3 || !known.some((name) => ANCHORS.has(name))) return [];

  const out: Finding[] = [];
  const counts = new Map<string, number>();

  for (const header of headers) {
    const rule = BY_NAME.get(header.name);
    if (!rule || header.value === '') continue;
    // Received appears once per relay. Numbering them keeps each hop visible
    // without the label repeating identically down the report.
    const seen = (counts.get(header.name) ?? 0) + 1;
    counts.set(header.name, seen);
    out.push({
      kind: rule.kind,
      confidence: rule.confidence,
      location: `mail header:${header.name}`,
      label: seen > 1 ? `${rule.label} ${seen}` : rule.label,
      value: header.value,
    });
  }

  // Any X- header the list does not know by name. These are where a pipeline
  // stamps itself — the field is a free-for-all by design, so enumerating the
  // ones seen so far would guarantee missing the next one.
  const listed = new Set(out.map((f) => f.location));
  for (const header of headers) {
    if (!header.name.startsWith('x-') || header.value === '') continue;
    if (listed.has(`mail header:${header.name}`)) continue;
    listed.add(`mail header:${header.name}`);
    out.push({
      kind: 'provenance',
      confidence: 'probable',
      location: `mail header:${header.name}`,
      label: `Non-standard header: ${header.name}`,
      value: header.value,
    });
  }

  return out;
}

/**
 * Headers that name the software rather than carry the message.
 *
 * These are the ones removal can touch. Everything else in the block — From,
 * To, Subject, Date, Message-ID — *is* the message: the person wrote it, the
 * recipient needs it, and threading breaks without it. Those are reported and
 * left alone, which is the same line this tool draws everywhere else between
 * metadata and content.
 */
const TOOL_HEADERS = new Set([
  'x-mailer',
  'user-agent',
  'x-generated-by',
  'x-generator',
  'x-originating-client',
  'x-ai-generated',
]);

const isToolHeader = (name: string) => TOOL_HEADERS.has(name) || name.startsWith('x-');

/**
 * Remove the header lines that name a tool, keeping the message intact.
 *
 * The whole line goes, not its value. A message with `X-Mailer:` present and
 * empty is not something any client sends, and the reasoning that removes an
 * emptied `/Info` dictionary from a PDF applies unchanged here: a blanked field
 * announces that someone blanked it. Plenty of real messages carry no
 * `X-Mailer` at all, so removing the line leaves an ordinary shape behind.
 *
 * Folded continuation lines go with the field they belong to, or a wrapped
 * `User-Agent` would leave half of itself behind in the block.
 */
export function stripToolHeaders(text: string): { text: string; removed: string[] } {
  const headers = parseBlock(text);
  if (!headers) return { text, removed: [] };

  const names = new Set(headers.map((h) => h.name));
  const known = [...names].filter((name) => BY_NAME.has(name) || ANCHORS.has(name));
  if (known.length < 3 || !known.some((name) => ANCHORS.has(name))) return { text, removed: [] };

  const removed: string[] = [];
  const lines = text.split(/\r?\n/);
  const kept: string[] = [];
  let dropping = false;
  let inBlock = true;

  for (const line of lines) {
    if (inBlock && line.trim() === '') {
      inBlock = false;
      kept.push(line);
      continue;
    }
    if (!inBlock) {
      kept.push(line);
      continue;
    }
    if (/^[ \t]/.test(line)) {
      // Continuation: it belongs to whatever the previous field decided.
      if (!dropping) kept.push(line);
      continue;
    }
    const match = FIELD.exec(line);
    if (match && isToolHeader(match[1]!.toLowerCase())) {
      dropping = true;
      removed.push(match[1]!);
      continue;
    }
    dropping = false;
    kept.push(line);
  }

  return { text: kept.join('\n'), removed };
}
