/**
 * Traces left by the tool that produced a document.
 *
 * A file generated by an assistant, an agent or a script rarely announces
 * itself in one field. It leaks in pieces: a producer string naming the
 * library, a template path holding the operating system and the account name,
 * a working directory under a session identifier. Read individually those look
 * innocuous; read together they describe the machine the document was made on.
 *
 * This module derives that picture from values already extracted elsewhere. It
 * adds no new parsing of the file — it reinterprets what the format modules
 * found, which is why every result here points back at the field it came from.
 */

import type { Finding } from './types.js';
import { declaresGenerative } from './sourcetype.js';

interface Signature {
  pattern: RegExp;
  label: string;
  /** Builds the reported value from the regex match. */
  describe: (match: RegExpMatchArray) => string;
  kind: Finding['kind'];
}

/**
 * Path shapes that identify an operating system and the account name.
 * The account name is the part that matters: it is usually a real person's
 * login, and it survives in template paths and hyperlinks long after the
 * author field has been cleared.
 */
const HOST_SIGNATURES: Signature[] = [
  {
    pattern: /(?:^|[^A-Za-z])([A-Za-z]):[\\/]Users[\\/]([^\\/:*?"<>|\s]+)/,
    label: 'Windows account',
    describe: (m) => `${m[2]} (drive ${m[1]}:)`,
    kind: 'environment',
  },
  {
    // The lookbehind matters: "file:///C:/Users/lotfi" is a Windows path
    // expressed as a URL, and without it every such link is misreported as a
    // macOS account. Only an unprefixed /Users/ is genuinely macOS.
    pattern: /(?<![A-Za-z]:)\/Users\/([^/\s]+)/,
    label: 'macOS account',
    describe: (m) => m[1]!,
    kind: 'environment',
  },
  {
    pattern: /\/home\/([^/\s]+)/,
    label: 'Linux account',
    describe: (m) => m[1]!,
    kind: 'environment',
  },
  {
    pattern: /\/mnt\/([a-z])\//,
    label: 'WSL mount',
    describe: (m) => `Windows drive ${m[1]!.toUpperCase()}: mounted under WSL`,
    kind: 'environment',
  },
];

/** Scratch locations, which reveal that the file was produced by a pipeline. */
const TEMP_SIGNATURES: Signature[] = [
  {
    pattern: /(?:AppData[\\/]Local[\\/]Temp|%TEMP%)/i,
    label: 'Windows temporary directory',
    describe: () => 'file was assembled in a scratch directory',
    kind: 'environment',
  },
  {
    pattern: /\/var\/folders\/[^\s"]*/,
    label: 'macOS temporary directory',
    describe: () => 'file was assembled in a scratch directory',
    kind: 'environment',
  },
  {
    pattern: /\/tmp\/[^\s"]*/,
    label: 'Temporary directory',
    describe: (m) => m[0]!,
    kind: 'environment',
  },
];

/** Identifiers that tie a document to one run or one workspace. */
const IDENTIFIER_SIGNATURES: Signature[] = [
  {
    pattern: /\bsession[_-]([A-Za-z0-9]{6,})/i,
    label: 'Session identifier',
    describe: (m) => m[0]!,
    kind: 'environment',
  },
  {
    pattern: /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i,
    label: 'Run or workspace identifier (UUID)',
    describe: (m) => m[0]!,
    kind: 'environment',
  },
];

/**
 * Producer strings that name the software behind the file.
 *
 * Two groups, because they answer different questions. An assistant or agent
 * name says the content was machine-generated; a document library says the file
 * was assembled programmatically rather than saved from Office, which is itself
 * a strong hint even when no model is named.
 */
const ASSISTANT_TOOLS: Array<[RegExp, string]> = [
  [/\bclaude\b|\banthropic\b/i, 'Claude / Anthropic'],
  [/\bchatgpt\b|\bopenai\b/i, 'ChatGPT / OpenAI'],
  [/\bgemini\b|\bbard\b|\bvertex\s*ai\b/i, 'Gemini / Vertex AI'],
  [/\bcopilot\b/i, 'GitHub Copilot'],
  [/\bmistral\b|\ble\s*chat\b/i, 'Mistral'],
  [/\bllama\b|\bmeta\s*ai\b/i, 'Llama / Meta AI'],
  [/\bperplexity\b/i, 'Perplexity'],
  [/\bdeepseek\b/i, 'DeepSeek'],
  [/\bgrok\b|\bx\.?ai\b/i, 'Grok / xAI'],
  [/\bqwen\b|\btongyi\b/i, 'Qwen'],
  [/\bcohere\b|\bcommand-r\b/i, 'Cohere'],
];

/** Coding agents and IDE assistants, which stamp files they write. */
const AGENT_TOOLS: Array<[RegExp, string]> = [
  [/claude[\s_-]?code/i, 'Claude Code'],
  [/\bcursor\b/i, 'Cursor'],
  [/\bwindsurf\b|\bcodeium\b/i, 'Windsurf / Codeium'],
  [/\bdevin\b/i, 'Devin'],
  [/\baider\b/i, 'Aider'],
  [/\bcline\b|\broo[\s-]?code\b/i, 'Cline / Roo Code'],
  [/\bbolt\.new\b/i, 'Bolt'],
  [/\bv0\.dev\b/i, 'v0'],
  [/replit[\s_-]?agent/i, 'Replit Agent'],
  [/\bcodex\b/i, 'Codex'],
  [/\bcontinue\.dev\b/i, 'Continue'],
];

/** Orchestration frameworks and local runtimes. */
const FRAMEWORK_TOOLS: Array<[RegExp, string]> = [
  [/langchain/i, 'LangChain'],
  [/llama[\s_-]?index/i, 'LlamaIndex'],
  [/autogen/i, 'AutoGen'],
  [/crew[\s_-]?ai/i, 'CrewAI'],
  [/haystack/i, 'Haystack'],
  [/semantic[\s_-]?kernel/i, 'Semantic Kernel'],
  [/\bollama\b/i, 'Ollama'],
  [/\bvllm\b/i, 'vLLM'],
  [/llama\.cpp/i, 'llama.cpp'],
  [/lm[\s_-]?studio/i, 'LM Studio'],
  [/huggingface|\btransformers\b/i, 'Hugging Face / transformers'],
];

/**
 * Model identifiers. These are more telling than a vendor name: they pin the
 * exact model and often the release date of the generation.
 */
const MODEL_IDENTIFIERS: Array<[RegExp, string]> = [
  [/\bclaude-(?:opus|sonnet|haiku|fable|instant)[\w.-]*/i, 'Claude'],
  [/\bgpt-[0-9][\w.-]*|\bo[134](?:-mini|-preview)?\b/i, 'OpenAI'],
  [/\bgemini-[\w.-]+/i, 'Gemini'],
  [/\bllama-?[0-9][\w.-]*/i, 'Llama'],
  [/\bmistral-[\w.-]+|\bmixtral-[\w.-]+/i, 'Mistral'],
  [/\bdeepseek-[\w.-]+/i, 'DeepSeek'],
  [/\bqwen[0-9.]*-[\w.-]+/i, 'Qwen'],
];

/**
 * Request, conversation and run identifiers emitted by provider APIs. They tie
 * a document to one specific call, which is stronger than naming the vendor.
 */
const API_IDENTIFIERS: Array<[RegExp, string]> = [
  [/\bmsg_[A-Za-z0-9]{16,}/, 'Anthropic message id'],
  [/\bchatcmpl-[A-Za-z0-9]{16,}/, 'OpenAI completion id'],
  [/\b(?:thread|asst|run|file)_[A-Za-z0-9]{16,}/, 'OpenAI assistant object id'],
  [/\breq_[A-Za-z0-9]{16,}/, 'API request id'],
  [/\bconv(?:ersation)?[_-][A-Za-z0-9]{12,}/i, 'Conversation id'],
];

/**
 * Credential shapes. A key left in a generated file is the most serious thing
 * this tool can find, so it is reported first and never printed in full.
 */
const CREDENTIALS: Array<[RegExp, string]> = [
  [/\bsk-ant-[A-Za-z0-9_-]{20,}/, 'Anthropic API key'],
  [/\bsk-proj-[A-Za-z0-9_-]{20,}/, 'OpenAI project key'],
  [/\bsk-[A-Za-z0-9]{32,}/, 'OpenAI-style API key'],
  [/\bAIza[A-Za-z0-9_-]{30,}/, 'Google API key'],
  [/\bhf_[A-Za-z0-9]{30,}/, 'Hugging Face token'],
  [/\bgsk_[A-Za-z0-9]{30,}/, 'Groq API key'],
  [/\bxai-[A-Za-z0-9]{20,}/, 'xAI API key'],
  [/\bghp_[A-Za-z0-9]{36}/, 'GitHub personal access token'],
];

/** Show enough of a secret to recognise it, never enough to use it. */
function mask(secret: string): string {
  const prefix = secret.slice(0, Math.min(10, secret.indexOf('-') + 1 || 6));
  return `${prefix}… (${secret.length} characters) — rotate this key`;
}

const AUTOMATION_TOOLS: Array<[RegExp, string]> = [
  [/python-pptx/i, 'python-pptx'],
  [/python-docx/i, 'python-docx'],
  [/openpyxl/i, 'openpyxl'],
  [/reportlab/i, 'ReportLab'],
  [/\bfpdf\b|\btcpdf\b|\bmpdf\b/i, 'FPDF / TCPDF / mPDF'],
  [/pandoc/i, 'Pandoc'],
  [/wkhtmltopdf/i, 'wkhtmltopdf'],
  [/weasyprint/i, 'WeasyPrint'],
  [/puppeteer/i, 'Puppeteer'],
  [/playwright/i, 'Playwright'],
  [/headless\s*chrom/i, 'Headless Chrome'],
  [/skia\/pdf/i, 'Skia (Chrome print-to-PDF)'],
  [/libreoffice|openoffice/i, 'LibreOffice / OpenOffice'],
  [/\baspose\b/i, 'Aspose'],
  [/pdf-lib/i, 'pdf-lib'],
  [/\bdocx\b\s*(?:js|npm)/i, 'docx (JavaScript)'],
];

interface ToolMatch {
  label: string;
  detail: string;
  kind: Finding['kind'];
}

function matchTool(value: string): ToolMatch[] {
  const matches: ToolMatch[] = [];
  const seen = new Set<string>();
  const add = (label: string, detail: string, kind: Finding['kind']) => {
    const key = `${label}:${detail}`;
    if (!seen.has(key)) {
      seen.add(key);
      matches.push({ label, detail, kind });
    }
  };

  for (const [pattern, name] of CREDENTIALS) {
    const found = pattern.exec(value);
    if (found) add(`Credential left in file: ${name}`, mask(found[0]), 'identity');
  }
  for (const [pattern, name] of API_IDENTIFIERS) {
    const found = pattern.exec(value);
    if (found) add(name, found[0], 'environment');
  }
  for (const [pattern, vendor] of MODEL_IDENTIFIERS) {
    const found = pattern.exec(value);
    if (found) add('Model identifier', `${found[0]} (${vendor})`, 'provenance');
  }
  for (const [pattern, tool] of AGENT_TOOLS) {
    if (pattern.test(value)) add('Coding agent named in metadata', tool, 'provenance');
  }
  for (const [pattern, tool] of ASSISTANT_TOOLS) {
    if (pattern.test(value)) add('Assistant or agent named in metadata', tool, 'provenance');
  }
  for (const [pattern, tool] of FRAMEWORK_TOOLS) {
    if (pattern.test(value)) add('LLM framework or runtime', tool, 'provenance');
  }
  for (const [pattern, tool] of AUTOMATION_TOOLS) {
    if (pattern.test(value)) add('Document generated programmatically', tool, 'provenance');
  }
  return matches;
}

/**
 * Derive host, tooling and session traces from findings already collected.
 *
 * Results are de-duplicated on label + value, because the same account name
 * typically appears in a template path and in several hyperlinks at once, and
 * reporting it five times helps nobody.
 */
export function fingerprint(findings: Finding[]): Finding[] {
  const derived = new Map<string, Finding>();

  const add = (finding: Finding) => {
    const key = `${finding.label}\x00${finding.value}`;
    if (!derived.has(key)) derived.set(key, finding);
  };

  for (const source of findings) {
    const value = source.value;
    if (!value) continue;

    for (const signature of [...HOST_SIGNATURES, ...TEMP_SIGNATURES, ...IDENTIFIER_SIGNATURES]) {
      const match = value.match(signature.pattern);
      if (!match) continue;
      add({
        kind: signature.kind,
        confidence: 'confirmed',
        location: `derived from ${source.location}`,
        label: signature.label,
        value: signature.describe(match),
      });
    }

    for (const tool of matchTool(value)) {
      add({
        kind: tool.kind,
        confidence: 'confirmed',
        location: `derived from ${source.location}`,
        label: tool.label,
        value: tool.detail,
      });
    }
  }

  return [...derived.values()];
}

/**
 * The one question a reader actually asks: was this made by an AI, and which?
 *
 * Everything needed is already in the findings — but spread over as many as
 * five rows among a dozen others, so answering it means assembling the report
 * by hand. This gathers them into one statement.
 *
 * The silent case is the one that matters most. A file with no such trace
 * produces no provenance row at all, and a report that simply says nothing
 * reads as "no AI" when the truthful answer is "nothing in the metadata says
 * so, which is not the same thing". Whoever wrote the document may have pasted
 * the text in by hand, or cleared the fields, or used a tool that writes none —
 * and the wording itself, where a statistical watermark lives, is not readable
 * here at all. So the absence is stated rather than left to be inferred.
 */
export interface Provenance {
  /** Tools the metadata names, most specific first. */
  tools: string[];
  /** True when at least one field attributes the file to an AI tool. */
  attributed: boolean;
  /**
   * True when the file states in the IPTC vocabulary that a trained model made
   * it. That is a declaration rather than an inference — the strongest thing a
   * report here can say, and the thing the EU AI Act's transparency rules are
   * written around.
   */
  declared: boolean;
  /**
   * True when nothing names a tool but the container's own shape says a
   * program built it. Narrower than an attribution and much stronger than
   * silence — see structuralGenerator in ooxml.ts for what it reads.
   */
  machineAssembled: boolean;
}

/** Labels this module emits that name a producing tool rather than a machine. */
const TOOL_LABELS = [
  'Model identifier',
  'Assistant or agent named in metadata',
  'Coding agent named in metadata',
  'LLM framework or runtime',
  // Credited by a signed manifest rather than inferred from a free-text field.
  'Tool credited by the C2PA manifest',
  'Software credited by the action',
  'Document generated programmatically',
  // The plainest statement a file can make about what wrote it. It is reported
  // as informational because naming Word is not a privacy problem — but a
  // summary that answers "what produced this" and omits the field literally
  // headed "Application" is answering the wrong question.
  'Producing application',
  'Creating application',
  'XMP creator tool',
] as const;

export function provenance(findings: Finding[]): Provenance {
  const tools: string[] = [];
  for (const label of TOOL_LABELS) {
    for (const finding of findings) {
      if (finding.label !== label) continue;
      // C2PA values carry their own caveat ("— asserted by the manifest,
      // signature not verified"), which belongs in the report line rather than
      // repeated after every tool name in a one-line summary.
      const name = finding.value.split(' \u2014 ')[0]!.trim();
      if (!name) continue;
      // The raw field often restates what an earlier, parsed entry already
      // said: "ReportLab" then "ReportLab PDF Library - www.reportlab.com",
      // "claude-opus-5 (Claude)" then "claude-opus-5 via LangChain 0.3.7". A
      // one-line answer that repeats itself twice is not an answer.
      const lower = name.toLowerCase();
      if (tools.some((t) => t.toLowerCase().includes(lower) || lower.includes(t.toLowerCase()))) {
        continue;
      }
      tools.push(name);
    }
  }
  // "Generated programmatically" alone means a library wrote the container —
  // ReportLab, python-docx — which is not by itself an AI. The attribution is
  // only claimed when something names an assistant, a model or an agent.
  const attributed = findings.some(
    (finding) =>
      finding.label === 'Model identifier' ||
      finding.label === 'Assistant or agent named in metadata' ||
      finding.label === 'Coding agent named in metadata',
  );
  const machineAssembled = findings.some(
    (finding) => finding.label === 'Assembled by a program, not typed in a word processor',
  );
  return {
    tools,
    attributed: attributed || declaresGenerative(findings),
    declared: declaresGenerative(findings),
    machineAssembled,
  };
}
